name: Deploy with gh-pages
on:
  push:
    branches: [main]
jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
